server:
  port: 9000   #定义端口

spring:
  datasource:
    #引入druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cjtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
dubbo:
  scan:
    basePackages: com.fxm    #指定dubbo的包路径
  application:
    name: provider-user     #指定服务名称(必须指定)
  registry:
    address: zookeeper://192.168.15.2:2181?backup=192.168.15.2:2182,192.168.15.2:2183
  protocol:  #指定协议
    name: dubbo  #使用dubbo协议(tcp-ip)  web-controller直接调用sso-Service
    port: 20880  #服务链接时的端口号

      
mybatis-plus:
  type-aliases-package: com.fxm.dubbo.pojo       #配置别名包路径
  mapper-locations: classpath:/mybatis/mappers/*.xml  #添加mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                #开启驼峰映射规则
